name: "Label pull request"
on:
  pull_request:
    branches:
      - master
      - develop
      - "release/**"
    types: [opened]
jobs:
  pr-labeler:
    name: "Auto label the Pull Reqest"
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
